str1=input("Enter string in small letters:")
print(str1.upper())
str2=input("Enter string in capital letters:")
print(str2.lower())
str3=input("Enter any string :")
print(str3.swapcase())
str4=input("Enter any string:")
length=len(str4)
print("No.of digits",length)
